# Use the official Node.js 14 image as base
FROM node:21-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock to the container
COPY package*.json ./

# Install dependencies using Yarn
RUN npm install

# Copy the rest of the application code
COPY . .

# Build TypeScript code
RUN npm run build

#Port at which your application runs
ENV PORT=8080

# Expose the port your app runs on
EXPOSE 8080

# Command to run the application
CMD ["node", "./dist/index.js"]